version: '3'
services:
  test:
    image: gpipeworker-test-placeholder:testing
    build:
      context: ../
      dockerfile: ./scripts/Dockerfile  # should be relative to context path
    entrypoint: ['/bin/bash', '-c', '-l']
    command: ['/bin/bash', '-c',  '-l', './scripts/wait-for-it.sh kafka:9092 -t 30 && go test -v --failfast ./...']
    environment:
      - DB_HOST=kafka
      - DB_NAME=gpw-test-ci
    depends_on:
      - zookeeper
      - kafka


  zookeeper:
    image: quay.io/strimzi/kafka:0.29.0-kafka-3.2.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.29.0-kafka-3.2.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
